In [1]:
import pandas as pd

In [3]:
file_path = r"D:\nava-ai\data\raw\online_retail_II.xlsx"
df = pd.read_excel(file_path)
df_clean = df.copy()

In [4]:
print("Original Data SHape:",df.shape)
print("Clean Data Shape:",df_clean.shape)

Original Data SHape: (525461, 8)
Clean Data Shape: (525461, 8)

In [5]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)
df_clean.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [9]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      525461 non-null  object
 1   stockcode    525461 non-null  object
 2   description  522533 non-null  object
 3   quantity     525461 non-null  int64
 4   invoicedate  525461 non-null  datetime64[us]
 5   price        525461 non-null  float64
 6   customer_id  417534 non-null  float64
 7   country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [12]:
df_clean["invoicedate"] = pd.to_datetime(
    df_clean["invoicedate"],
    errors="coerce"
)
#df_clean["invoicedate"].head()
df_clean["quantity"] = pd.to_numeric(
    df_clean["quantity"],
    errors="coerce"
)
df_clean["price"] = pd.to_numeric(
    df_clean["quantity"],
    errors="coerce"
)
df_clean["customer_id"] = pd.to_numeric(
    df_clean["quantity"],
    errors="coerce"
)

In [14]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      525461 non-null  object
 1   stockcode    525461 non-null  object
 2   description  522533 non-null  object
 3   quantity     525461 non-null  int64
 4   invoicedate  525461 non-null  datetime64[us]
 5   price        525461 non-null  int64
 6   customer_id  525461 non-null  int64
 7   country      525461 non-null  str
dtypes: datetime64[us](1), int64(3), object(3), str(1)
memory usage: 32.1+ MB

In [17]:
duplicate_count=df_clean.duplicated().sum()
print("Duplicate count:",duplicate_count)
duplicate_percentage = (
    duplicate_count / len(df_clean) * 100
)

print(
    f"Duplicate percentage: {duplicate_percentage:.2f}%"
)

Duplicate count: 6979
Duplicate percentage: 1.33%

In [19]:
duplicate_rows = df_clean[
    df_clean.duplicated(keep=False)
].sort_values(
    by=["invoice", "stockcode", "invoicedate"]
)

duplicate_rows.head(20)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1,1,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1,1,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,1,1,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,1,1,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,1,1,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,1,1,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,1,1,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,1,1,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,1,1,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,6,6,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,6,6,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,12,12,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,12,12,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,1,1,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,1,1,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,12,12,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,12,12,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,12,12,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,12,12,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,1,1,United Kingdom

In [18]:
duplicate_groups = (
    df_clean
    .groupby(
        [
            "invoice",
            "stockcode",
            "description",
            "quantity",
            "invoicedate",
            "price",
            "customer_id",
            "country"
        ],
        dropna=False
    )
    .size()
)

duplicate_groups[
    duplicate_groups > 1
].sort_values(
    ascending=False
).head(20)

invoice  stockcode  description                          quantity  invoicedate          price  customer_id  country
C514024  M          Manual                               -1        2010-06-30 11:22:00  -1     -1           United Kingdom    8
C528093  S          SAMPLES                              -1        2010-10-20 13:21:00  -1     -1           United Kingdom    7
C506607  S          SAMPLES                              -1        2010-04-30 15:28:00  -1     -1           United Kingdom    7
502660   17021      NAMASTE SWAGAT INCENSE                6        2010-03-25 17:18:00   6      6           United Kingdom    6
496431   84826      ASSTD DESIGN 3D PAPER STICKERS        1        2010-02-01 12:30:00   1      1           United Kingdom    6
C535663  D          Discount                             -1        2010-11-28 11:41:00  -1     -1           United Kingdom    6
525065   20894      HANGING BAUBLE T-LIGHT HOLDER LARGE   1        2010-10-03 14:28:00   1      1           United Kingdom    6
534219   35953      FOLKART STAR CHRISTMAS DECORATIONS    1        2010-11-21 16:13:00   1      1           United Kingdom    6
520570   21754      HOME BUILDING BLOCK WORD              1        2010-08-26 20:07:00   1      1           United Kingdom    5
         21755      LOVE BUILDING BLOCK WORD              1        2010-08-26 20:07:00   1      1           United Kingdom    5
492784   22114      HOT WATER BOTTLE TEA AND SYMPATHY     1        2009-12-18 17:24:00   1      1           United Kingdom    5
501425   85040B     SET/4 BLUE FLOWER CANDLES IN BOWL     1        2010-03-16 12:00:00   1      1           United Kingdom    5
C516614  S          SAMPLES                              -1        2010-07-21 14:49:00  -1     -1           United Kingdom    5
530953   21231      SWEETHEART CERAMIC TRINKET BOX        4        2010-11-04 18:42:00   4      4           United Kingdom    5
532679   22264      FELT FARM ANIMAL WHITE BUNNY          1        2010-11-14 12:17:00   1      1           United Kingdom    5
537224   70007      HI TEC ALPINE HAND WARMER             1        2010-12-05 16:24:00   1      1           United Kingdom    5
C506602  S          SAMPLES                              -1        2010-04-30 14:56:00  -1     -1           United Kingdom    5
499542   22253      6 CROCHET STRAWBERRIES                1        2010-03-01 11:59:00   1      1           United Kingdom    4
507394   84839      SWEETHEART KEY CABINET                1        2010-05-09 12:49:00   1      1           United Kingdom    4
503774   21550      CERAMIC BIRDHOUSE CRESTED TIT LARGE   1        2010-04-07 11:04:00   1      1           United Kingdom    4
dtype: int64

In [20]:
before = len(df_clean)

df_clean = df_clean.drop_duplicates()

after = len(df_clean)

print("Rows before:", before)
print("Rows after :", after)
print("Rows removed:", before - after)
print("Remaining duplicates:", df_clean.duplicated().sum())

Rows before: 525461
Rows after : 518482
Rows removed: 6979
Remaining duplicates: 0

In [22]:
missing_summary = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing %": (
        df_clean.isna().sum() / len(df_clean) * 100
    )
})

missing_summary

             Missing Count  Missing %
invoice                  0   0.000000
stockcode                0   0.000000
description           2928   0.564725
quantity                 0   0.000000
invoicedate              0   0.000000
price                    0   0.000000
customer_id              0   0.000000
country                  0   0.000000

In [24]:
print("Missing Customer IDs:",
      df_clean["customer_id"].isnull().sum())

print("Missing Descriptions:",
      df_clean["description"].isnull().sum())

Missing Customer IDs: 0
Missing Descriptions: 2928

In [25]:
missing_description = df_clean[
    df_clean["description"].isna()
]

print("Rows with missing Description:",
      len(missing_description))

Rows with missing Description: 2928

In [26]:
missing_description[
    [
        "invoice",
        "stockcode",
        "quantity",
        "invoicedate",
        "price",
        "customer_id",
        "country"
    ]
].head(30)

,invoice,stockcode,quantity,invoicedate,price,customer_id,country
470,489521,21646,-50,2009-12-01 11:44:00,-50,-50,United Kingdom
3114,489655,20683,-44,2009-12-01 17:26:00,-44,-44,United Kingdom
3161,489659,21350,230,2009-12-01 17:39:00,230,230,United Kingdom
3731,489781,84292,17,2009-12-02 11:45:00,17,17,United Kingdom
4296,489806,18010,-770,2009-12-02 12:42:00,-770,-770,United Kingdom
4566,489821,85049G,-240,2009-12-02 13:25:00,-240,-240,United Kingdom
6378,489882,35751C,12,2009-12-02 16:22:00,12,12,United Kingdom
6555,489898,79323G,954,2009-12-03 09:40:00,954,954,United Kingdom
6576,489901,21098,-200,2009-12-03 09:47:00,-200,-200,United Kingdom
6581,489903,21166,48,2009-12-03 09:57:00,48,48,United Kingdom
7204,490015,21982,467,2009-12-03 12:29:00,467,467,United Kingdom
7205,490016,21982,-1012,2009-12-03 12:30:00,-1012,-1012,United Kingdom
7559,490055,20620,-25,2009-12-03 13:22:00,-25,-25,United Kingdom
8553,490084,85064,-89,2009-12-03 15:37:00,-89,-89,United Kingdom
9249,490123,84508B,184,2009-12-03 18:08:00,184,184,United Kingdom
9667,490146,21558,-169,2009-12-04 09:29:00,-169,-169,United Kingdom
10236,490150,84347,80,2009-12-04 09:44:00,80,80,United Kingdom
10508,490165,21493,-106,2009-12-04 11:32:00,-106,-106,United Kingdom
11973,490354,21489,-23,2009-12-04 16:39:00,-23,-23,United Kingdom
12237,490379,21490,-44,2009-12-05 13:26:00,-44,-44,United Kingdom
12299,490384,84721,-42,2009-12-05 14:00:00,-42,-42,United Kingdom
14480,490540,37446,-725,2009-12-07 09:24:00,-725,-725,United Kingdom
14503,490543,37446,222,2009-12-07 09:45:00,222,222,United Kingdom
15489,490688,21133,270,2009-12-07 13:50:00,270,270,United Kingdom
15883,490713,84347,-20,2009-12-07 15:26:00,-20,-20,United Kingdom
15908,490715,22158,-30,2009-12-07 15:27:00,-30,-30,United Kingdom
15952,490716,22158,6,2009-12-07 15:28:00,6,6,United Kingdom
16185,490735,35976B,-60,2009-12-07 17:12:00,-60,-60,United Kingdom
16186,490736,35983,-200,2009-12-07 17:13:00,-200,-200,United Kingdom
17384,490758,72008,3000,2009-12-08 09:38:00,3000,3000,United Kingdom

In [27]:
missing_desc_codes = df_clean.loc[
    df_clean["description"].isna(),
    "stockcode"
].unique()

print("Unique StockCodes with missing Description:",
      len(missing_desc_codes))

missing_desc_codes[:20]

Unique StockCodes with missing Description: 1920

array([21646, 20683, 21350, 84292, 18010, '85049G', '35751C', '79323G',
       21098, 21166, 21982, 20620, 85064, '84508B', 21558, 84347, 21493,
       21489, 21490, 84721], dtype=object)

In [28]:
description_lookup = (
    df_clean.groupby("stockcode")["description"].first()
)

df_clean["description"] = (
    df_clean["description"]
    .fillna(df_clean["stockcode"].map(description_lookup))
)

In [29]:
print("Missing descriptions:",
      df_clean["description"].isna().sum())

Missing descriptions: 365

In [30]:
df_clean[
    df_clean["description"].isna()
][
    ["stockcode", "description"]
].head(20)

      stockcode description
470       21646         NaN
16186     35983         NaN
19313     84571         NaN
20975     35949         NaN
22854    17013A         NaN
23542     84841         NaN
32106    72752C         NaN
32109    72755B         NaN
32110    72752D         NaN
43528    35751A         NaN
43583    71263G         NaN
43623     20691         NaN
43625     20880         NaN
43626     20859         NaN
43629     72777         NaN
43635    79069A         NaN
43640    84247B         NaN
43641    84986A         NaN
43687    35980A         NaN
43688     84940         NaN