In [3]:
import pandas as pd
import numpy as np

In [4]:
file_path = r"D:\nava-ai\data\raw\online_retail_II.xlsx"
df = pd.read_excel(file_path)
df_clean = df.copy()

In [5]:
print("Original Data SHape:",df.shape)
print("Clean Data Shape:",df_clean.shape)

Original Data SHape: (525461, 8)
Clean Data Shape: (525461, 8)

In [6]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
)
df_clean.columns

Index(['invoice', 'stockcode', 'description', 'quantity', 'invoicedate',
       'price', 'customer_id', 'country'],
      dtype='str')

In [7]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      525461 non-null  object
 1   stockcode    525461 non-null  object
 2   description  522533 non-null  object
 3   quantity     525461 non-null  int64
 4   invoicedate  525461 non-null  datetime64[us]
 5   price        525461 non-null  float64
 6   customer_id  417534 non-null  float64
 7   country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [8]:
df_clean["invoicedate"] = pd.to_datetime(
    df_clean["invoicedate"],
    errors="coerce"
)
#df_clean["invoicedate"].head()
df_clean["quantity"] = pd.to_numeric(
    df_clean["quantity"],
    errors="coerce"
)
df_clean["price"] = pd.to_numeric(
    df_clean["price"],
    errors="coerce"
)
df_clean["customer_id"] = pd.to_numeric(
    df_clean["customer_id"],
    errors="coerce"
)

In [9]:
df_clean["customer_id"]

0         13085.0
1         13085.0
2         13085.0
3         13085.0
4         13085.0
           ...
525456    17530.0
525457    17530.0
525458    17530.0
525459    17530.0
525460    17530.0
Name: customer_id, Length: 525461, dtype: float64

In [10]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   invoice      525461 non-null  object
 1   stockcode    525461 non-null  object
 2   description  522533 non-null  object
 3   quantity     525461 non-null  int64
 4   invoicedate  525461 non-null  datetime64[us]
 5   price        525461 non-null  float64
 6   customer_id  417534 non-null  float64
 7   country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [11]:
duplicate_count=df_clean.duplicated().sum()
print("Duplicate count:",duplicate_count)
duplicate_percentage = (
    duplicate_count / len(df_clean) * 100
)

print(
    f"Duplicate percentage: {duplicate_percentage:.2f}%"
)

Duplicate count: 6865
Duplicate percentage: 1.31%

In [12]:
duplicate_rows = df_clean[
    df_clean.duplicated(keep=False)
].sort_values(
    by=["invoice", "stockcode", "invoicedate"]
)

duplicate_rows.head(20)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom

In [13]:
duplicate_groups = (
    df_clean
    .groupby(
        [
            "invoice",
            "stockcode",
            "description",
            "quantity",
            "invoicedate",
            "price",
            "customer_id",
            "country"
        ],
        dropna=False
    )
    .size()
)

duplicate_groups[
    duplicate_groups > 1
].sort_values(
    ascending=False
).head(20)

invoice  stockcode  description                          quantity  invoicedate          price  customer_id  country
496431   84826      ASSTD DESIGN 3D PAPER STICKERS       1         2010-02-01 12:30:00  0.85   16415.0      United Kingdom    6
502660   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 17:18:00  0.30   13187.0      United Kingdom    6
525065   20894      HANGING BAUBLE T-LIGHT HOLDER LARGE  1         2010-10-03 14:28:00  2.95   16799.0      United Kingdom    6
534219   35953      FOLKART STAR CHRISTMAS DECORATIONS   1         2010-11-21 16:13:00  1.25   13230.0      United Kingdom    6
492784   22114      HOT WATER BOTTLE TEA AND SYMPATHY    1         2009-12-18 17:24:00  3.95   17841.0      United Kingdom    5
501425   85040B     SET/4 BLUE FLOWER CANDLES IN BOWL    1         2010-03-16 12:00:00  1.65   17774.0      United Kingdom    5
520570   21755      LOVE BUILDING BLOCK WORD             1         2010-08-26 20:07:00  5.95   16549.0      United Kingdom    5
         21754      HOME BUILDING BLOCK WORD             1         2010-08-26 20:07:00  5.95   16549.0      United Kingdom    5
530953   21231      SWEETHEART CERAMIC TRINKET BOX       4         2010-11-04 18:42:00  1.25   18168.0      United Kingdom    5
537224   70007      HI TEC ALPINE HAND WARMER            1         2010-12-05 16:24:00  1.65   13174.0      United Kingdom    5
532679   22264      FELT FARM ANIMAL WHITE BUNNY         1         2010-11-14 12:17:00  0.85   16960.0      United Kingdom    5
497921   22072      TEA CUP AND SAUCER RETRO SPOT        1         2010-02-14 15:38:00  3.75   14869.0      United Kingdom    4
491967   22147      FELTCRAFT BUTTERFLY HEARTS           1         2009-12-14 17:34:00  1.45   17012.0      United Kingdom    4
498352   22087      PAPER BUNTING WHITE LACE             1         2010-02-18 12:36:00  2.95   12898.0      United Kingdom    4
499542   22253      6 CROCHET STRAWBERRIES               1         2010-03-01 11:59:00  1.25   14131.0      United Kingdom    4
506388   79029      GLASS HONEYPOT WASP CATCHER          1         2010-04-29 12:51:00  1.95   16383.0      United Kingdom    4
507394   84839      SWEETHEART KEY CABINET               1         2010-05-09 12:49:00  6.75   16466.0      United Kingdom    4
490300   21726      MULTI HEARTS  STICKERS               1         2009-12-04 14:19:00  0.85   12970.0      United Kingdom    4
522089   22604      SET OF 4 NAPKIN CHARMS CUTLERY       1         2010-09-12 12:41:00  2.55   16387.0      United Kingdom    4
502534   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 11:32:00  0.30   15547.0      United Kingdom    4
dtype: int64

In [14]:
before = len(df_clean)

df_clean = df_clean.drop_duplicates()

after = len(df_clean)

print("Rows before:", before)
print("Rows after :", after)
print("Rows removed:", before - after)
print("Remaining duplicates:", df_clean.duplicated().sum())

Rows before: 525461
Rows after : 518596
Rows removed: 6865
Remaining duplicates: 0

In [15]:
missing_summary = pd.DataFrame({
    "Missing Count": df_clean.isnull().sum(),
    "Missing %": (
        df_clean.isna().sum() / len(df_clean) * 100
    )
})

missing_summary

             Missing Count  Missing %
invoice                  0   0.000000
stockcode                0   0.000000
description           2928   0.564601
quantity                 0   0.000000
invoicedate              0   0.000000
price                    0   0.000000
customer_id         107833  20.793257
country                  0   0.000000

In [16]:
print("Missing Customer IDs:",
      df_clean["customer_id"].isnull().sum())

print("Missing Descriptions:",
      df_clean["description"].isnull().sum())

Missing Customer IDs: 107833
Missing Descriptions: 2928

In [17]:
missing_description = df_clean[
    df_clean["description"].isna()
]

print("Rows with missing Description:",
      len(missing_description))

Rows with missing Description: 2928

In [18]:
missing_description[
    [
        "invoice",
        "stockcode",
        "quantity",
        "invoicedate",
        "price",
        "customer_id",
        "country"
    ]
].head(30)

,invoice,stockcode,quantity,invoicedate,price,customer_id,country
470,489521,21646,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
3161,489659,21350,230,2009-12-01 17:39:00,0.0,NaN,United Kingdom
3731,489781,84292,17,2009-12-02 11:45:00,0.0,NaN,United Kingdom
4296,489806,18010,-770,2009-12-02 12:42:00,0.0,NaN,United Kingdom
4566,489821,85049G,-240,2009-12-02 13:25:00,0.0,NaN,United Kingdom
6378,489882,35751C,12,2009-12-02 16:22:00,0.0,NaN,United Kingdom
6555,489898,79323G,954,2009-12-03 09:40:00,0.0,NaN,United Kingdom
6576,489901,21098,-200,2009-12-03 09:47:00,0.0,NaN,United Kingdom
6581,489903,21166,48,2009-12-03 09:57:00,0.0,NaN,United Kingdom
7204,490015,21982,467,2009-12-03 12:29:00,0.0,NaN,United Kingdom
7205,490016,21982,-1012,2009-12-03 12:30:00,0.0,NaN,United Kingdom
7559,490055,20620,-25,2009-12-03 13:22:00,0.0,NaN,United Kingdom
8553,490084,85064,-89,2009-12-03 15:37:00,0.0,NaN,United Kingdom
9249,490123,84508B,184,2009-12-03 18:08:00,0.0,NaN,United Kingdom
9667,490146,21558,-169,2009-12-04 09:29:00,0.0,NaN,United Kingdom
10236,490150,84347,80,2009-12-04 09:44:00,0.0,NaN,United Kingdom
10508,490165,21493,-106,2009-12-04 11:32:00,0.0,NaN,United Kingdom
11973,490354,21489,-23,2009-12-04 16:39:00,0.0,NaN,United Kingdom
12237,490379,21490,-44,2009-12-05 13:26:00,0.0,NaN,United Kingdom
12299,490384,84721,-42,2009-12-05 14:00:00,0.0,NaN,United Kingdom
14480,490540,37446,-725,2009-12-07 09:24:00,0.0,NaN,United Kingdom
14503,490543,37446,222,2009-12-07 09:45:00,0.0,NaN,United Kingdom
15489,490688,21133,270,2009-12-07 13:50:00,0.0,NaN,United Kingdom
15883,490713,84347,-20,2009-12-07 15:26:00,0.0,NaN,United Kingdom
15908,490715,22158,-30,2009-12-07 15:27:00,0.0,NaN,United Kingdom
15952,490716,22158,6,2009-12-07 15:28:00,0.0,NaN,United Kingdom
16185,490735,35976B,-60,2009-12-07 17:12:00,0.0,NaN,United Kingdom
16186,490736,35983,-200,2009-12-07 17:13:00,0.0,NaN,United Kingdom
17384,490758,72008,3000,2009-12-08 09:38:00,0.0,NaN,United Kingdom

In [19]:
missing_desc_codes = df_clean.loc[
    df_clean["description"].isna(),
    "stockcode"
].unique()

print("Unique StockCodes with missing Description:",
      len(missing_desc_codes))

missing_desc_codes[:20]

Unique StockCodes with missing Description: 1920

array([21646, 20683, 21350, 84292, 18010, '85049G', '35751C', '79323G',
       21098, 21166, 21982, 20620, 85064, '84508B', 21558, 84347, 21493,
       21489, 21490, 84721], dtype=object)

In [20]:
description_lookup = (
    df_clean.groupby("stockcode")["description"].first()
)

df_clean["description"] = (
    df_clean["description"]
    .fillna(df_clean["stockcode"].map(description_lookup))
)

In [21]:
print("Missing descriptions:",
      df_clean["description"].isna().sum())

Missing descriptions: 365

In [22]:
df_clean[
    df_clean["description"].isna()
][
    ["stockcode", "description"]
].head(20)

      stockcode description
470       21646         NaN
16186     35983         NaN
19313     84571         NaN
20975     35949         NaN
22854    17013A         NaN
23542     84841         NaN
32106    72752C         NaN
32109    72755B         NaN
32110    72752D         NaN
43528    35751A         NaN
43583    71263G         NaN
43623     20691         NaN
43625     20880         NaN
43626     20859         NaN
43629     72777         NaN
43635    79069A         NaN
43640    84247B         NaN
43641    84986A         NaN
43687    35980A         NaN
43688     84940         NaN

**Handling the negative quantity**

In [23]:
df_clean["transaction_type"] = np.where(
    df_clean["quantity"] < 0,
    "Return/Cancel",
    "Sale"
)

In [24]:
df_clean.head(20)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Sale
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Sale
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,Sale
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,Sale
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,Sale
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,Sale
10,489435,22195,HEART MEASURING SPOONS LARGE,24,2009-12-01 07:46:00,1.65,13085.0,United Kingdom,Sale
11,489435,22353,LUNCHBOX WITH CUTLERY FAIRY CAKES,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,Sale
12,489436,48173C,DOOR MAT BLACK FLOCK,10,2009-12-01 09:06:00,5.95,13078.0,United Kingdom,Sale
13,489436,21755,LOVE BUILDING BLOCK WORD,18,2009-12-01 09:06:00,5.45,13078.0,United Kingdom,Sale
14,489436,21754,HOME BUILDING BLOCK WORD,3,2009-12-01 09:06:00,5.95,13078.0,United Kingdom,Sale
15,489436,84879,ASSORTED COLOUR BIRD ORNAMENT,16,2009-12-01 09:06:00,1.69,13078.0,United Kingdom,Sale
16,489436,22119,PEACE WOODEN BLOCK LETTERS,3,2009-12-01 09:06:00,6.95,13078.0,United Kingdom,Sale
17,489436,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-01 09:06:00,1.45,13078.0,United Kingdom,Sale
18,489436,22296,HEART IVORY TRELLIS LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom,Sale
19,489436,22295,HEART FILIGREE DOVE LARGE,12,2009-12-01 09:06:00,1.65,13078.0,United Kingdom,Sale

In [25]:
df_clean["transaction_type"].value_counts()

transaction_type
Sale             506294
Return/Cancel     12302
Name: count, dtype: int64

**Fixing the issue of custoemr_id**

In [26]:
df.loc[178:186, ["Invoice", "StockCode", "Quantity", "Price", "Customer ID"]]

     Invoice StockCode  Quantity  Price  Customer ID
178  C489449     22087       -12   2.95      16321.0
179  C489449    85206A        -6   1.65      16321.0
180  C489449     21895        -4   4.25      16321.0
181  C489449     21896        -6   2.10      16321.0
182  C489449     22083       -12   2.95      16321.0
183  C489449     21871       -12   1.25      16321.0
184  C489449     84946       -12   1.25      16321.0
185  C489449    84970S       -24   0.85      16321.0
186  C489449     22090       -12   2.95      16321.0

In [27]:
df_clean["customer_id"] = df.loc[
    df_clean.index, "Customer ID"
]

In [28]:
df_clean["customer_id"].head()

0    13085.0
1    13085.0
2    13085.0
3    13085.0
4    13085.0
Name: customer_id, dtype: float64

**Negative price handling**

In [29]:
negative_price = df_clean[df_clean["price"] < 0]

negative_price[
    [
        "invoice",
        "stockcode",
        "description",
        "quantity",
        "price",
        "customer_id",
        "country"
    ]
].head(30)

,invoice,stockcode,description,quantity,price,customer_id,country
179403,A506401,B,Adjust bad debt,1,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,-38925.87,NaN,United Kingdom

In [32]:
print("Negative price rows:", (df_clean["price"] < 0).sum())

Negative price rows: 3

In [33]:
negative_price["invoice"].astype(str).str[0].value_counts()

invoice
A    3
Name: count, dtype: int64

In [34]:
negative_price[
    ~negative_price["invoice"].astype(str).str.startswith("C")
][
    [
        "invoice",
        "stockcode",
        "description",
        "quantity",
        "price",
        "customer_id",
        "country"
    ]
].head(30)

,invoice,stockcode,description,quantity,price,customer_id,country
179403,A506401,B,Adjust bad debt,1,-53594.36,NaN,United Kingdom
276274,A516228,B,Adjust bad debt,1,-44031.79,NaN,United Kingdom
403472,A528059,B,Adjust bad debt,1,-38925.87,NaN,United Kingdom

In [59]:
negative_price[
    ~negative_price["invoice"].astype(str).str.startswith("C")
]["description"].value_counts().head(20)

description
?                                     43
damages                               39
damaged                               36
missing                               24
given away                             7
dotcom                                 6
smashed                                5
checked                                5
MIA                                    4
Damages                                4
WALL MOUNTED VINTAGE ORGANISER         4
ebay sales                             4
crushed                                4
short                                  3
BLUE WHITE SCARF HOT WATER BOTTLE      3
SET OF THREE 50'S GIFT WRAPS           3
ASSORTED COLOUR JUMBO PEN              3
POLYESTER FILLER PAD 45x45cm           3
PINK 3 PIECE MINI DOTS CUTLERY SET     3
BLUE FLORIBUNDA EGG WARMER             3
Name: count, dtype: int64

In [49]:
df_clean["price_status"] = np.where(
    df_clean["price"] < 0,
    "Invalid/Adjustment Price",
    "Valid Price"
)
df_clean.tail(30)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type,sales_revenue,...,net_revenue,date,year,month,month_name,day,day_of_week,hour,is_weekend,price_status
525431,538171,22416,SET OF 36 DOILIES SPACEBOY DESIGN,1,2010-12-09 20:01:00,1.45,17530.0,United Kingdom,Sale,1.45,...,1.45,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525432,538171,21211,SET OF 72 SKULL PAPER DOILIES,1,2010-12-09 20:01:00,1.45,17530.0,United Kingdom,Sale,1.45,...,1.45,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525433,538171,22367,CHILDRENS APRON SPACEBOY DESIGN,4,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,Sale,7.80,...,7.80,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525434,538171,21156,RETROSPOT CHILDRENS APRON,1,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,Sale,1.95,...,1.95,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525435,538171,47591D,PINK FAIRY CAKE CHILDRENS APRON,1,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,Sale,1.95,...,1.95,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525436,538171,47591B,SCOTTIES CHILDRENS APRON,2,2010-12-09 20:01:00,1.65,17530.0,United Kingdom,Sale,3.30,...,3.30,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525437,538171,22899,CHILDREN'S APRON DOLLY GIRL,1,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,2.10,...,2.10,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525438,538171,21908,CHOCOLATE THIS WAY METAL SIGN,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,4.20,...,4.20,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525439,538171,21905,MORE BUTTER METAL SIGN,1,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,2.10,...,2.10,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525440,538171,21989,PACK OF 20 SKULL PAPER NAPKINS,2,2010-12-09 20:01:00,0.85,17530.0,United Kingdom,Sale,1.70,...,1.70,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525441,538171,22837,HOT WATER BOTTLE BABUSHKA,2,2010-12-09 20:01:00,4.65,17530.0,United Kingdom,Sale,9.30,...,9.30,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525442,538171,85152,HAND OVER THE CHOCOLATE SIGN,3,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,6.30,...,6.30,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525443,538171,21329,DINOSAURS WRITING SET,2,2010-12-09 20:01:00,1.65,17530.0,United Kingdom,Sale,3.30,...,3.30,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525444,538171,21327,SKULLS WRITING SET,2,2010-12-09 20:01:00,1.65,17530.0,United Kingdom,Sale,3.30,...,3.30,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525445,538171,22666,RECIPE BOX PANTRY YELLOW DESIGN,1,2010-12-09 20:01:00,2.95,17530.0,United Kingdom,Sale,2.95,...,2.95,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525446,538171,22154,ANGEL DECORATION 3 BUTTONS,48,2010-12-09 20:01:00,0.42,17530.0,United Kingdom,Sale,20.16,...,20.16,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525447,538171,21875,KINGS CHOICE MUG,2,2010-12-09 20:01:00,1.25,17530.0,United Kingdom,Sale,2.50,...,2.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525448,538171,21871,SAVE THE PLANET MUG,2,2010-12-09 20:01:00,1.25,17530.0,United Kingdom,Sale,2.50,...,2.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525449,538171,21877,HOME SWEET HOME MUG,2,2010-12-09 20:01:00,1.25,17530.0,United Kingdom,Sale,2.50,...,2.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525450,538171,22747,POPPY'S PLAYHOUSE BATHROOM,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,4.20,...,4.20,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525451,538171,22748,POPPY'S PLAYHOUSE KITCHEN,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,4.20,...,4.20,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525452,538171,22745,POPPY'S PLAYHOUSE BEDROOM,2,2010-12-09 20:01:00,2.10,17530.0,United Kingdom,Sale,4.20,...,4.20,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525453,538171,22558,CLOTHES PEGS RETROSPOT PACK 24,4,2010-12-09 20:01:00,1.49,17530.0,United Kingdom,Sale,5.96,...,5.96,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525454,538171,21671,RED SPOT CERAMIC DRAWER KNOB,6,2010-12-09 20:01:00,1.25,17530.0,United Kingdom,Sale,7.50,...,7.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525455,538171,20971,PINK BLUE FELT CRAFT TRINKET BOX,2,2010-12-09 20:01:00,1.25,17530.0,United Kingdom,Sale,2.50,...,2.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom,Sale,5.90,...,5.90,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,3.75,...,3.75,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,3.75,...,3.75,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,7.50,...,7.50,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,Sale,3.90,...,3.90,2010-12-09,2010,12,December,9,Thursday,20,False,Valid Price

**Revenue Generation**

**---> Sales Revenue**

In [35]:
df_clean["sales_revenue"] = np.where(
    (df_clean["quantity"] > 0) & (df_clean["price"] > 0),
    df_clean["quantity"] * df_clean["price"],
    0
)
df_clean.head(10)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type,sales_revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Sale,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Sale,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale,30.0
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,Sale,39.6
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale,30.0
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,Sale,59.5
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,Sale,30.6
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,Sale,45.0

**---> Return Revenue**

In [36]:
df_clean["return_amount"] = np.where(
    (df_clean["quantity"] < 0) & (df_clean["price"] > 0),
    abs(df_clean["quantity"] * df_clean["price"]),
    0
)
df_clean.tail()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type,sales_revenue,return_amount
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom,Sale,5.90,0.0
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,3.75,0.0
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,3.75,0.0
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom,Sale,7.50,0.0
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom,Sale,3.90,0.0

**---> Net Revenue**

In [37]:
df_clean["net_revenue"] = (
    df_clean["sales_revenue"] - df_clean["return_amount"]
)
df_clean.head()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type,sales_revenue,return_amount,net_revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Sale,83.4,0.0,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0,0.0,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0,0.0,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Sale,100.8,0.0,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale,30.0,0.0,30.0

**Date and time features generation**

In [38]:
df_clean["date"] = df_clean["invoicedate"].dt.date

In [39]:
df_clean["year"] = df_clean["invoicedate"].dt.year

In [40]:
df_clean["month"] = df_clean["invoicedate"].dt.month

In [41]:
df_clean["month_name"] = df_clean["invoicedate"].dt.month_name()

In [42]:
df_clean["day"] = df_clean["invoicedate"].dt.day

In [43]:
df_clean["day_of_week"] = df_clean["invoicedate"].dt.day_name()

In [44]:
df_clean["hour"] = df_clean["invoicedate"].dt.hour

In [45]:
df_clean["is_weekend"] = (
    df_clean["invoicedate"].dt.dayofweek >= 5
)

In [46]:
df_clean.head(10)

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,country,transaction_type,sales_revenue,return_amount,net_revenue,date,year,month,month_name,day,day_of_week,hour,is_weekend
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,Sale,83.4,0.0,83.4,2009-12-01,2009,12,December,1,Tuesday,7,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0,0.0,81.0,2009-12-01,2009,12,December,1,Tuesday,7,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,Sale,81.0,0.0,81.0,2009-12-01,2009,12,December,1,Tuesday,7,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,Sale,100.8,0.0,100.8,2009-12-01,2009,12,December,1,Tuesday,7,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale,30.0,0.0,30.0,2009-12-01,2009,12,December,1,Tuesday,7,False
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,Sale,39.6,0.0,39.6,2009-12-01,2009,12,December,1,Tuesday,7,False
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,Sale,30.0,0.0,30.0,2009-12-01,2009,12,December,1,Tuesday,7,False
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,Sale,59.5,0.0,59.5,2009-12-01,2009,12,December,1,Tuesday,7,False
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,Sale,30.6,0.0,30.6,2009-12-01,2009,12,December,1,Tuesday,7,False
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,Sale,45.0,0.0,45.0,2009-12-01,2009,12,December,1,Tuesday,7,False

**Encoding the neceassary features**

In [47]:
df_clean.select_dtypes(include="object").columns

C:\Users\gansh\AppData\Local\Temp\ipykernel_2624\432708615.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_clean.select_dtypes(include="object").columns

Index(['invoice', 'stockcode', 'description', 'country', 'transaction_type',
       'date', 'month_name', 'day_of_week'],
      dtype='str')

In [50]:
categorical_columns = [
    "country",
    "transaction_type",
    "price_status"
]

df_clean = pd.get_dummies(
    df_clean,
    columns=categorical_columns,
    dtype=int
)

In [79]:
df_clean.tail()

,invoice,stockcode,description,quantity,invoicedate,price,customer_id,sales_revenue,return_amount,net_revenue,...,country_Thailand,country_USA,country_United Arab Emirates,country_United Kingdom,country_Unspecified,country_West Indies,transaction_type_Return/Cancel,transaction_type_Sale,price_status_Invalid/Adjustment Price,price_status_Valid Price
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2,17530.0,4,0,4,...,0,0,0,1,0,0,0,1,0,1
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,1,17530.0,1,0,1,...,0,0,0,1,0,0,0,1,0,1
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,1,17530.0,1,0,1,...,0,0,0,1,0,0,0,1,0,1
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,2,17530.0,4,0,4,...,0,0,0,1,0,0,0,1,0,1
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,2,17530.0,4,0,4,...,0,0,0,1,0,0,0,1,0,1

In [51]:
print("Shape:", df_clean.shape)

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:", df_clean.duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)

Shape: (518596, 62)

Missing values:
invoice                                    0
stockcode                                  0
description                              365
quantity                                   0
invoicedate                                0
                                        ...
country_West Indies                        0
transaction_type_Return/Cancel             0
transaction_type_Sale                      0
price_status_Invalid/Adjustment Price      0
price_status_Valid Price                   0
Length: 62, dtype: int64

Duplicate rows: 0

Data types:
invoice                                          object
stockcode                                        object
description                                      object
quantity                                          int64
invoicedate                              datetime64[us]
                                              ...
country_West Indies                               int64
transaction_type_Return/Cancel                    int64
transaction_type_Sale                             int64
price_status_Invalid/Adjustment Price             int64
price_status_Valid Price                          int64
Length: 62, dtype: object

In [52]:
df_clean.to_excel("retail_buisness_cleaned_data.xlsx", index=False)